// ============================================================
// SRI MANIKANTA POOJA STORES — DYNAMICALLY GENERATED DATA
// This file is auto-generated by the backend admin panel.
// ============================================================

const PRODUCTS = [
    {
        "id": 5005,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Balaji Bindu Premium Incense Sticks",
        "telugu": "బాలాజీ బిందు ప్రీమియం అగర్బత్తి",
        "price": 70,
        "originalPrice": 90,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090833.jpg",
        "images": [
            "images/1000090833.jpg"
        ],
        "description": "Balaji Bindu Premium Incense Sticks – by Balaji Since 1957. Zipper-lock pouch for extra freshness. Premium quality incense for a divine, long-lasting fragrance experience during pooja.",
        "sizes": [
            "Standard Pouch"
        ],
        "tags": [
            "balaji",
            "bindu",
            "premium",
            "zipper lock",
            "fresh"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 5004,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Ambica Durbar Bathi New Pack",
        "telugu": "అంబికా దర్బార్ బత్తి న్యూ ప్యాక్",
        "price": 70,
        "originalPrice": 85,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090832.jpg",
        "images": [
            "images/1000090832.jpg"
        ],
        "description": "Ambica Durbar Bathi New Pack – India&#039;s only Herbal Durbar Bathi in a fresh new packaging. Hand rolled blend of 63 herbs. A new look for the same trusted traditional quality.",
        "sizes": [
            {
                "name": "New Pack",
                "price": 70,
                "original_price": 85,
                "stock": 100,
                "image": ""
            }
        ],
        "tags": [],
        "badge": "new",
        "inStock": true,
        "featured": false
    },
    {
        "id": 5003,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Ambica Durbar Bathi 75g",
        "telugu": "అంబికా దర్బార్ బత్తి 75గ్రా",
        "price": 60,
        "originalPrice": 75,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090831.jpg",
        "images": [
            "images/1000090831.jpg"
        ],
        "description": "Ambica Durbar Bathi 75g – India's only Herbal Durbar Bathi. Hand rolled with 63 herbs blend. Compact 75g pack ideal for regular daily use.",
        "sizes": [
            "75g Pack"
        ],
        "tags": [
            "ambica",
            "durbar",
            "herbal",
            "75g"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 5002,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Ambica Durbar Bathi 145g",
        "telugu": "అంబికా దర్బార్ బత్తి 145గ్రా",
        "price": 70,
        "originalPrice": 90,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090830.jpg",
        "images": [
            "images/1000090830.jpg"
        ],
        "description": "Ambica Durbar Bathi 145g – India's only Herbal Durbar Bathi in a larger 145g pack. Hand rolled using a traditional blend of 63 herbs for a long-lasting, divine fragrance.",
        "sizes": [
            "145g Pack"
        ],
        "tags": [
            "ambica",
            "durbar",
            "herbal",
            "145g",
            "large pack"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 5001,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Ambica Durbar Bathi (Herbal)",
        "telugu": "అంబికా దర్బార్ బత్తి",
        "price": 60,
        "originalPrice": 75,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090829.jpg",
        "images": [
            "images/1000090829.jpg"
        ],
        "description": "Ambica Durbar Bathi – India's only Herbal Durbar Bathi. Hand rolled in India using a mix of 63 herbs. By ACP Industries Ltd., Eluru. A traditional herbal incense loved for generations.",
        "sizes": [
            "Standard Pack"
        ],
        "tags": [
            "ambica",
            "durbar",
            "herbal",
            "63 herbs",
            "hand rolled"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 41,
        "category": "wedding",
        "categoryName": "Wedding Items",
        "name": "Mangalsutra Thread (Dhaarana)",
        "telugu": "మంగళసూత్రం దారం",
        "price": 150,
        "originalPrice": 220,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090826.jpg",
        "images": [
            "images/1000090826.jpg"
        ],
        "description": "Traditional yellow mangalsutra dhaaranu thread with turmeric powder and kumkum. Pure cotton, sacred yellow thread for wedding and Varalakshmi puja.",
        "sizes": [
            "Standard",
            "With Pendant Space"
        ],
        "tags": [
            "mangalsutra",
            "wedding",
            "auspicious"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 40,
        "category": "wedding",
        "categoryName": "Wedding Items",
        "name": "Kankana Dhara Thread Set",
        "telugu": "కంకణ ధారణ సెట్",
        "price": 299,
        "originalPrice": 420,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090825.jpg",
        "images": [
            "images/1000090825.jpg"
        ],
        "description": "Sacred kankanam wrist thread for bride and groom. Yellow silk thread with turmeric, janeu sacred thread included. Traditional Telugu wedding ritual item.",
        "sizes": [
            "Standard Pack (2 sets)",
            "Family Pack (5 sets)"
        ],
        "tags": [
            "kankanam",
            "wedding",
            "sacred thread"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 39,
        "category": "wedding",
        "categoryName": "Wedding Items",
        "name": "Telugu Wedding Samagri Kit",
        "telugu": "వివాహ సామగ్రి కిట్",
        "price": 1499,
        "originalPrice": 2200,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090824.jpg",
        "images": [
            "images/1000090824.jpg"
        ],
        "description": "Complete Telugu Brahmin wedding puja kit. Includes: coconut, beetle leaves & nuts, mango leaves, sacred thread, turmeric pieces, bangles, sacred cloth, kankanam thread, akshat, and all ritual items as per Telugu Shastras.",
        "sizes": [
            "Basic",
            "Complete",
            "Premium Deluxe"
        ],
        "tags": [
            "wedding",
            "vivah",
            "complete",
            "telugu"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 38,
        "category": "festivals",
        "categoryName": "Festival Kits",
        "name": "Ugadi Puja Kit",
        "telugu": "ఉగాది పూజా కిట్",
        "price": 349,
        "originalPrice": 499,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090831.jpg",
        "images": [
            "images/1000090831.jpg"
        ],
        "description": "Complete Telugu New Year (Ugadi) kit with neem flowers, jaggery, mango pieces, tamarind, chilli and all 6 rasa (taste) items plus puja essentials.",
        "sizes": [
            "Small",
            "Family Pack"
        ],
        "tags": [
            "ugadi",
            "telugu new year",
            "festival"
        ],
        "badge": "new",
        "inStock": true,
        "featured": false
    },
    {
        "id": 37,
        "category": "festivals",
        "categoryName": "Festival Kits",
        "name": "Diwali Puja Complete Kit",
        "telugu": "దీపావళి పూజా కిట్",
        "price": 649,
        "originalPrice": 950,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090830.jpg",
        "images": [
            "images/1000090830.jpg"
        ],
        "description": "Complete Diwali puja kit with: clay diyas (set of 20), camphor, Lakshmi idol, rangoli colors, kumkum, haldi, dhoop, flowers, mauli thread and puja booklet.",
        "sizes": [
            "Standard",
            "Premium"
        ],
        "tags": [
            "diwali",
            "lakshmi puja",
            "complete kit"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 36,
        "category": "festivals",
        "categoryName": "Festival Kits",
        "name": "Vinayaka Chavithi Complete Kit",
        "telugu": "వినాయక చవితి కిట్",
        "price": 549,
        "originalPrice": 799,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090829.jpg",
        "images": [
            "images/1000090829.jpg"
        ],
        "description": "All-in-one Ganesh Chaturthi kit: includes modak plate, 21-durva grass, red thread (janeu), dhoop, incense, kumkum, haldi, flowers, coconut and complete puja booklet in Telugu & English.",
        "sizes": [
            "Basic",
            "Premium",
            "Deluxe"
        ],
        "tags": [
            "ganesh chaturthi",
            "complete kit",
            "festival"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 35,
        "category": "havan",
        "categoryName": "Havan Samagri",
        "name": "Copper Havan Kund",
        "telugu": "హవన్ కుండ్",
        "price": 899,
        "originalPrice": 1299,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090828.jpg",
        "images": [
            "images/1000090828.jpg"
        ],
        "description": "Pure copper havan kund for performing Agni puja and homam at home. Traditional pyramid shape, durable copper, easy to clean, comes with stand.",
        "sizes": [
            {
                "name": "Small (6",
                "price": 899,
                "original_price": 1299,
                "stock": 100,
                "image": ""
            },
            {
                "name": "Medium (9",
                "price": 899,
                "original_price": 1299,
                "stock": 100,
                "image": ""
            },
            {
                "name": "Large (12",
                "price": 899,
                "original_price": 1299,
                "stock": 100,
                "image": ""
            }
        ],
        "tags": [],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 34,
        "category": "havan",
        "categoryName": "Havan Samagri",
        "name": "Havan Samagri Mix (Premium)",
        "telugu": "హవన్ సామగ్రి",
        "price": 199,
        "originalPrice": 280,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090827.jpg",
        "images": [
            "images/1000090827.jpg"
        ],
        "description": "Premium blend of 51 sacred herbs and materials for havan/homam. Includes sandalwood, ghee-soaked cotton wicks, guggul, camphor, and more. Rich fragrance, pure ingredients.",
        "sizes": [
            {
                "name": "100g",
                "price": 199,
                "original_price": 280,
                "stock": 100,
                "image": ""
            },
            {
                "name": "250g",
                "price": 199,
                "original_price": 280,
                "stock": 100,
                "image": ""
            },
            {
                "name": "500g",
                "price": 199,
                "original_price": 280,
                "stock": 100,
                "image": ""
            },
            {
                "name": "1kg",
                "price": 199,
                "original_price": 280,
                "stock": 100,
                "image": ""
            }
        ],
        "tags": [],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 33,
        "category": "malas",
        "categoryName": "Malas & Rosaries",
        "name": "Marigold Flower Garland",
        "telugu": "బంతి పూల మాల",
        "price": 50,
        "originalPrice": 70,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090826.jpg",
        "images": [
            "images/1000090826.jpg"
        ],
        "description": "Artificial marigold flower garland for deity decoration. Premium quality silk-finish flowers, vibrant orange/yellow. Reusable, long-lasting, no maintenance required.",
        "sizes": [
            "2 ft",
            "4 ft",
            "6 ft"
        ],
        "tags": [
            "marigold",
            "decoration",
            "garland"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 32,
        "category": "malas",
        "categoryName": "Malas & Rosaries",
        "name": "Tulsi Mala (Holy Basil)",
        "telugu": "తులసి మాల",
        "price": 150,
        "originalPrice": 220,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090825.jpg",
        "images": [
            "images/1000090825.jpg"
        ],
        "description": "Sacred Tulsi mala for Vishnu and Krishna japa. Made from genuine Vrindavan Tulsi beads. 108 + 1 beads, smooth finish, auspicious for daily chanting.",
        "sizes": [
            "Standard (108 beads)"
        ],
        "tags": [
            "tulsi",
            "krishna",
            "vishnu",
            "japa"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 31,
        "category": "malas",
        "categoryName": "Malas & Rosaries",
        "name": "Rudraksha Mala (108 beads)",
        "telugu": "రుద్రాక్ష మాల",
        "price": 599,
        "originalPrice": 850,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090824.jpg",
        "images": [
            "images/1000090824.jpg"
        ],
        "description": "Authentic 5-mukhi Rudraksha mala with 108 beads for japa and meditation. Energized and blessed. Genuine Indonesian rudraksha, knotted between each bead, silver guru bead.",
        "sizes": [
            "Small Bead (6mm)",
            "Medium Bead (8mm)",
            "Large Bead (10mm)"
        ],
        "tags": [
            "rudraksha",
            "japa",
            "meditation",
            "shiva"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 27,
        "category": "idols",
        "categoryName": "Idols (Vigrahas)",
        "name": "Saraswati Brass Idol",
        "telugu": "సరస్వతి విగ్రహం",
        "price": 899,
        "originalPrice": 1200,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090830.jpg",
        "images": [
            "images/1000090830.jpg"
        ],
        "description": "Goddess Saraswati brass idol with Veena (musical instrument). Perfect for Saraswati Puja and Navratri. Fine craftsmanship, antique brass finish.",
        "sizes": [
            "4 inch",
            "6 inch",
            "8 inch"
        ],
        "tags": [
            "saraswati",
            "navratri",
            "education"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 26,
        "category": "idols",
        "categoryName": "Idols (Vigrahas)",
        "name": "Lakshmi Idol (Silver Plated)",
        "telugu": "లక్ష్మీదేవి విగ్రహం",
        "price": 1299,
        "originalPrice": 1699,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090829.jpg",
        "images": [
            "images/1000090829.jpg"
        ],
        "description": "Beautiful silver-plated Goddess Lakshmi idol in standing posture. Exquisite craftsmanship, pure silver coating, elegant finish. Brings divine blessings and prosperity.",
        "sizes": [
            "3 inch",
            "5 inch",
            "7 inch"
        ],
        "tags": [
            "lakshmi",
            "silver plated",
            "gifting"
        ],
        "badge": "new",
        "inStock": true,
        "featured": true
    },
    {
        "id": 25,
        "category": "idols",
        "categoryName": "Idols (Vigrahas)",
        "name": "Brass Ganesha Idol (4 inch)",
        "telugu": "గణేశ విగ్రహం",
        "price": 799,
        "originalPrice": 1099,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090828.jpg",
        "images": [
            "images/1000090828.jpg"
        ],
        "description": "Hand-crafted pure brass Lord Ganesha idol, 4-inch seated Ganesha. Intricate detailing, smooth finish, auspicious idol for home temple. Ideal for gifting and installation.",
        "sizes": [
            "2 inch",
            "4 inch",
            "6 inch",
            "8 inch"
        ],
        "tags": [
            "ganesha",
            "brass idol",
            "handcrafted"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 24,
        "category": "photos",
        "categoryName": "God Photos & Frames",
        "name": "Navgraha (9 Planets) Frame",
        "telugu": "నవగ్రహ దేవతలు",
        "price": 350,
        "originalPrice": 480,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090827.jpg",
        "images": [
            "images/1000090827.jpg"
        ],
        "description": "All nine planet deities in one beautiful frame. Essential for navgraha puja and home altar. Premium print, gold border frame.",
        "sizes": [
            "8×10 inch",
            "12×15 inch"
        ],
        "tags": [
            "navgraha",
            "nine planets",
            "special puja"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 22,
        "category": "photos",
        "categoryName": "God Photos & Frames",
        "name": "Goddess Lakshmi Photo Frame",
        "telugu": "లక్ష్మీదేవి ఫోటో",
        "price": 250,
        "originalPrice": 350,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090825.jpg",
        "images": [
            "images/1000090825.jpg"
        ],
        "description": "Auspicious Goddess Lakshmi photo with golden border frame. High-resolution divine image, premium print on canvas board. Brings prosperity and blessings to your home.",
        "sizes": [
            "4×6 inch",
            "6×8 inch",
            "8×10 inch",
            "12×15 inch"
        ],
        "tags": [
            "lakshmi",
            "prosperity",
            "home blessing"
        ],
        "badge": null,
        "inStock": true,
        "featured": true
    },
    {
        "id": 21,
        "category": "photos",
        "categoryName": "God Photos & Frames",
        "name": "Lord Ganesha Photo Frame",
        "telugu": "గణేశ ఫోటో ఫ్రేమ్",
        "price": 250,
        "originalPrice": 350,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090824.jpg",
        "images": [
            "images/1000090824.jpg"
        ],
        "description": "Beautiful Lord Ganesha photo in premium wooden frame with glass. High-quality print with vibrant colors. Available in multiple sizes. Ideal for puja room, office and gifting.",
        "sizes": [
            "4×6 inch",
            "6×8 inch",
            "8×10 inch",
            "12×15 inch"
        ],
        "tags": [
            "ganesha",
            "photo frame",
            "gifting"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 19,
        "category": "diyas",
        "categoryName": "Diyas & Lamps",
        "name": "Pancha Mukhi Deepam",
        "telugu": "పంచముఖి దీపం",
        "price": 450,
        "originalPrice": 599,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090832.jpg",
        "images": [
            "images/1000090832.jpg"
        ],
        "description": "Five-faced brass deepam for special pujas and navaratri. Each face represents a different deity. Heavy antique-finish brass, premium craftsmanship.",
        "sizes": [
            "Medium",
            "Large"
        ],
        "tags": [
            "pancha mukhi",
            "navaratri",
            "special puja"
        ],
        "badge": "new",
        "inStock": true,
        "featured": false
    },
    {
        "id": 18,
        "category": "diyas",
        "categoryName": "Diyas & Lamps",
        "name": "Clay Diyas (Mitti Diya)",
        "telugu": "మట్టి దీపాలు",
        "price": 60,
        "originalPrice": 80,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090831.jpg",
        "images": [
            "images/1000090831.jpg"
        ],
        "description": "Handmade earthen clay diyas for Diwali and all festivals. Pack of 20 small diyas. Made by traditional artisans. Eco-friendly, natural clay, auspicious orange color.",
        "sizes": [
            "Pack of 10",
            "Pack of 20",
            "Pack of 50",
            "Pack of 100"
        ],
        "tags": [
            "diwali",
            "clay diya",
            "eco-friendly"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 17,
        "category": "diyas",
        "categoryName": "Diyas & Lamps",
        "name": "Brass Deepam (5-inch)",
        "telugu": "పితల దీపం",
        "price": 299,
        "originalPrice": 399,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090830.jpg",
        "images": [
            "images/1000090830.jpg"
        ],
        "description": "Traditional 5-inch brass deepam for daily worship. Elegant design, heavy base, holds ghee or oil. Polished brass surface, tarnish resistant. Perfect for home puja room.",
        "sizes": [
            "Single",
            "Set of 2",
            "Set of 5"
        ],
        "tags": [
            "brass diya",
            "deepam",
            "daily puja"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 10,
        "category": "kumkum",
        "categoryName": "Kumkum & Haldi",
        "name": "Pure Haldi (Turmeric) Powder",
        "telugu": "పసుపు",
        "price": 30,
        "originalPrice": 42,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090833.jpg",
        "images": [
            "images/1000090833.jpg"
        ],
        "description": "Bright yellow turmeric powder of highest purity. Used for tilak, haldi ceremony, warding off evil eye and skin care. Naturally sourced, pure grade quality.",
        "sizes": [
            "50g",
            "100g",
            "250g",
            "500g",
            "1kg"
        ],
        "tags": [
            "haldi ceremony",
            "tilak",
            "pure"
        ],
        "badge": null,
        "inStock": true,
        "featured": true
    },
    {
        "id": 9,
        "category": "kumkum",
        "categoryName": "Kumkum & Haldi",
        "name": "Premium Red Kumkum",
        "telugu": "కుంకుమ",
        "price": 25,
        "originalPrice": 35,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090832.jpg",
        "images": [
            "images/1000090832.jpg"
        ],
        "description": "Pure, bright red kumkum made from natural turmeric and lime. Fine texture, vibrant color, long-lasting. Essential for tilak, goddess worship and all religious ceremonies.",
        "sizes": [
            "25g",
            "50g",
            "100g",
            "250g",
            "500g"
        ],
        "tags": [
            "tilak",
            "goddess",
            "daily puja"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 8,
        "category": "camphor",
        "categoryName": "Camphor (Kapoor)",
        "name": "Camphor Aarti Lamp Refill  90",
        "telugu": "కర్పూర్ ఆరతి",
        "price": 120,
        "originalPrice": 150,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090831.jpg",
        "images": [
            "images/1000090831.jpg"
        ],
        "description": "Premium camphor cubes specially shaped for brass aarti lamps. Consistent size, pure grade camphor. Pack includes 24 large cubes for extended puja sessions.",
        "sizes": [
            {
                "name": "Pack of 12",
                "price": 120,
                "original_price": 150,
                "stock": 100,
                "image": ""
            },
            {
                "name": "Pack of 24",
                "price": 120,
                "original_price": 150,
                "stock": 100,
                "image": ""
            }
        ],
        "tags": [],
        "badge": "new",
        "inStock": true,
        "featured": false
    },
    {
        "id": 7,
        "category": "camphor",
        "categoryName": "Camphor (Kapoor)",
        "name": "Camphor Powder (Loose)",
        "telugu": "కర్పూరం పొడి",
        "price": 55,
        "originalPrice": 70,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090830.jpg",
        "images": [
            "images/1000090830.jpg"
        ],
        "description": "Fine camphor powder for havan and special rituals. Dissolves quickly and produces divine fragrance. Used in traditional Telugu and South Indian ceremonies.",
        "sizes": [
            "50g",
            "100g",
            "250g"
        ],
        "tags": [
            "havan",
            "powder",
            "ritual"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 5,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Zed Black Luxury Fresh Pineapple Incense Sticks",
        "telugu": "జెడ్ బ్లాక్ లక్జరీ ఫ్రెష్ పైనాపిల్ అగర్బత్తి",
        "price": 70,
        "originalPrice": 90,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090828.jpg",
        "images": [
            "images/1000090828.jpg"
        ],
        "description": "Zed Black Luxury Fresh Pineapple Premium Incense Sticks – charcoal-free incense with a refreshing, exotic pineapple fragrance. Premium luxury range for a truly uplifting prayer experience.",
        "sizes": [
            "Standard Pack"
        ],
        "tags": [
            "zed black",
            "luxury",
            "pineapple",
            "charcoal free"
        ],
        "badge": null,
        "inStock": true,
        "featured": false
    },
    {
        "id": 4,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Darshan Black Stone Incense Sticks",
        "telugu": "దర్శన్ బ్లాక్ స్టోన్ అగర్బత్తి",
        "price": 60,
        "originalPrice": 80,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090827.jpg",
        "images": [
            "images/1000090827.jpg"
        ],
        "description": "Darshan Black Stone Incense Sticks – a unique, unmatched fragrance (Ek Anokhi Khushboo). Dark premium packaging with gold mandala design. Perfect for meditation and evening prayers.",
        "sizes": [
            "Standard Pack"
        ],
        "tags": [
            "darshan",
            "black stone",
            "unique fragrance",
            "meditation"
        ],
        "badge": null,
        "inStock": true,
        "featured": true
    },
    {
        "id": 3,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Darshan White Stone Incense Sticks",
        "telugu": "దర్శన్ వైట్ స్టోన్ అగర్బత్తి",
        "price": 60,
        "originalPrice": 80,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090826.jpg",
        "images": [
            "images/1000090826.jpg"
        ],
        "description": "Darshan White Stone Incense Sticks – manufactured using enchanting perfumes in combination with natural oils to give power to your prayer and concentration for meditation. Elegant floral-patterned packaging.",
        "sizes": [
            "Standard Pack"
        ],
        "tags": [
            "darshan",
            "white stone",
            "meditation",
            "natural oils"
        ],
        "badge": "new",
        "inStock": true,
        "featured": true
    },
    {
        "id": 2,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Balaji 100 Divine Agarbathi 4IN1",
        "telugu": "బాలాజీ 100 డివైన్ అగర్బత్తి",
        "price": 70,
        "originalPrice": 90,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090825.jpg",
        "images": [
            "images/1000090825.jpg"
        ],
        "description": "Balaji 100 Divine Agarbathi – Super Strong Premium Fragrance 4IN1 blend. Since 1957, Balaji brings you the finest quality incense. Premium Gold range for a truly divine experience.",
        "sizes": [
            "Standard Pack"
        ],
        "tags": [
            "balaji",
            "4-in-1",
            "super strong",
            "premium gold"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    },
    {
        "id": 1,
        "category": "agarbatti",
        "categoryName": "Agarbatti & Incense",
        "name": "Zed Black 3-IN-1 Premium Agarbatti",
        "telugu": "జెడ్ బ్లాక్ 3-IN-1 అగర్బత్తి",
        "price": 60,
        "originalPrice": 80,
        "rating": 0,
        "reviews": 0,
        "image": "images/1000090824.jpg",
        "images": [
            "images/1000090824.jpg"
        ],
        "description": "Zed Black Premium 3-IN-1 Agarbatti – a triple fragrance blend in one pack. Long-lasting divine scent for daily puja. Brand ambassador MS Dhoni. Comes with a free matchbox inside.",
        "sizes": [
            "Standard Pack"
        ],
        "tags": [
            "zed black",
            "3-in-1",
            "premium",
            "daily puja"
        ],
        "badge": "popular",
        "inStock": true,
        "featured": true
    }
];

const CATEGORIES = [
    {
        "id": "agarbatti",
        "name": "Agarbatti & Incense",
        "telugu": "అగర్బత్తి",
        "img": "images/cat_agarbatti.png",
        "desc": "",
        "emoji": "🕉️",
        "count": 10
    },
    {
        "id": "camphor",
        "name": "Camphor (Kapoor)",
        "telugu": "కర్పూరం",
        "img": "images/cat_diyas.png",
        "desc": "",
        "emoji": "✨",
        "count": 2
    },
    {
        "id": "kumkum",
        "name": "Kumkum & Haldi",
        "telugu": "కుంకుమ పసుపు",
        "img": "images/cat_kumkum.png",
        "desc": "",
        "emoji": "🔴",
        "count": 2
    },
    {
        "id": "oils",
        "name": "Pooja Oils & Ghee",
        "telugu": "నూనె & నెయ్యి",
        "img": "images/cat_oils.png",
        "desc": "",
        "emoji": "🪔",
        "count": 0
    },
    {
        "id": "diyas",
        "name": "Diyas & Lamps",
        "telugu": "దీపాలు",
        "img": "images/cat_diyas.png",
        "desc": "",
        "emoji": "🪔",
        "count": 3
    },
    {
        "id": "photos",
        "name": "God Photos & Frames",
        "telugu": "దేవుడి ఫోటోలు",
        "img": "images/cat_idols.png",
        "desc": "",
        "emoji": "🖼️",
        "count": 3
    },
    {
        "id": "idols",
        "name": "Idols (Vigrahas)",
        "telugu": "విగ్రహాలు",
        "img": "images/cat_idols.png",
        "desc": "",
        "emoji": "🗿",
        "count": 3
    },
    {
        "id": "thali",
        "name": "Puja Thali & Vessels",
        "telugu": "పూజా పాత్రలు",
        "img": "images/cat_thali.png",
        "desc": "",
        "emoji": "🍽️",
        "count": 0
    },
    {
        "id": "malas",
        "name": "Malas & Rosaries",
        "telugu": "మాలలు",
        "img": "images/cat_malas.png",
        "desc": "",
        "emoji": "📿",
        "count": 3
    },
    {
        "id": "havan",
        "name": "Havan Samagri",
        "telugu": "హవన్ సామగ్రి",
        "img": "images/cat_festival.png",
        "desc": "",
        "emoji": "🔥",
        "count": 2
    },
    {
        "id": "festivals",
        "name": "Festival Kits",
        "telugu": "పండుగ కిట్లు",
        "img": "images/cat_festival.png",
        "desc": "",
        "emoji": "🎉",
        "count": 3
    },
    {
        "id": "wedding",
        "name": "Wedding Items",
        "telugu": "వివాహ సామగ్రి",
        "img": "images/cat_wedding.png",
        "desc": "",
        "emoji": "💍",
        "count": 3
    },
    {
        "id": "dhoop-sticks",
        "name": "Dhoop Sticks",
        "telugu": "",
        "img": "images/1000090824.jpg",
        "desc": "",
        "emoji": "🌸",
        "count": 0
    },
    {
        "id": "more-and-other",
        "name": "More and other",
        "telugu": "",
        "img": "images/1000090824.jpg",
        "desc": "",
        "emoji": "🌸",
        "count": 0
    }
];

const FESTIVALS = [
  { cat: 'festivals', color: '#ff9900', emoji: '🪔', name: 'Diwali', telugu: 'దీపావళి', date: 'Nov 12' },
  { cat: 'festivals', color: '#ff5500', emoji: '🐘', name: 'Ganesh Chaturthi', telugu: 'వినాయక చవితి', date: 'Sep 18' },
  { cat: 'festivals', color: '#00aa55', emoji: '🥭', name: 'Ugadi', telugu: 'ఉగాది', date: 'Mar 22' }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PRODUCTS, CATEGORIES, FESTIVALS };
}
