<?php
// ── HELPER: Regenerate js/products.js ───────────────────────────────────────────
// This function pulls the latest categories and products from the database and
// formats them as static JS arrays (window.PRODUCTS and window.CATEGORIES) 
// to keep the frontend incredibly fast while syncing with the backend.

function regenerate_products_js() {
    global $pdo;
    if (!$pdo) {
        require_once __DIR__ . '/../../config/database.php';
        $pdo = db();
    }

    // Emoji Map for default emojis based on slug
    $emojiMap = [
        'agarbatti' => '🕉️', 'camphor' => '✨', 'kumkum' => '🔴',
        'oils' => '🪔', 'diyas' => '🪔', 'photos' => '🖼️',
        'idols' => '🗿', 'thali' => '🍽️', 'malas' => '📿',
        'havan' => '🔥', 'festivals' => '🎉', 'wedding' => '💍'
    ];

    // 1. Fetch Categories
    $stmt = $pdo->query("SELECT * FROM categories WHERE is_active = 1 ORDER BY sort_order ASC");
    $cats = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Calculate product counts
    $stmtCount = $pdo->query("SELECT category_id, COUNT(id) as cnt FROM products WHERE is_active = 1 AND is_deleted = 0 GROUP BY category_id");
    $counts = [];
    while ($row = $stmtCount->fetch(PDO::FETCH_ASSOC)) {
        $counts[$row['category_id']] = (int)$row['cnt'];
    }
    
    $jsCategories = [];
    foreach ($cats as $c) {
        $slug = $c['slug'];
        $jsCategories[] = [
            'id' => $slug,
            'name' => $c['name'],
            'telugu' => $c['telugu'] ?? '',
            'img' => $c['image'] ?? 'images/1000090824.jpg',
            'desc' => $c['description'] ?? '',
            'emoji' => $emojiMap[$slug] ?? '🌸',
            'count' => $counts[$c['id']] ?? 0
        ];
    }

    // 2. Fetch Products
    $stmt = $pdo->query("
        SELECT p.*, c.slug AS cat_slug, c.name AS cat_name 
        FROM products p 
        JOIN categories c ON c.id = p.category_id 
        WHERE p.is_active = 1 AND p.is_deleted = 0
        ORDER BY p.id DESC
    ");
    $prods = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $jsProducts = [];
    foreach ($prods as $p) {
        $images = json_decode($p['images'] ?? '[]', true);
        $primaryImage = !empty($images) && is_array($images) ? $images[0] : 'images/1000090824.jpg';
        
        $jsProducts[] = [
            'id' => (int)$p['id'],
            'category' => $p['cat_slug'],
            'categoryName' => $p['cat_name'],
            'name' => $p['name'],
            'telugu' => $p['telugu_name'] ?? '',
            'price' => (float)$p['price'],
            'originalPrice' => $p['original_price'] !== null ? (float)$p['original_price'] : null,
            'rating' => (float)($p['rating'] ?? 4.5),
            'reviews' => (int)($p['review_count'] ?? 0),
            'image' => $primaryImage,
            'images' => $images,
            'description' => $p['description'] ?? '',
            'sizes' => json_decode($p['sizes'] ?? '[]', true),
            'tags' => json_decode($p['tags'] ?? '[]', true),
            'badge' => $p['badge'] ?? null,
            'inStock' => (int)$p['stock_qty'] > 0,
            'featured' => (bool)$p['is_featured']
        ];
    }

    // 3. Generate JS File Content
    $jsContent = "// ============================================================\n";
    $jsContent .= "// SRI MANIKANTA POOJA STORES — DYNAMICALLY GENERATED DATA\n";
    $jsContent .= "// This file is auto-generated by the backend admin panel.\n";
    $jsContent .= "// ============================================================\n\n";

    // Products Array
    $jsContent .= "const PRODUCTS = " . json_encode($jsProducts, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . ";\n\n";
    
    // Categories Array
    $jsContent .= "const CATEGORIES = " . json_encode($jsCategories, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . ";\n\n";
    
    // Festivals Array (Static fallback since it was in the original file)
    $jsContent .= "const FESTIVALS = [\n";
    $jsContent .= "  { cat: 'festivals', color: '#ff9900', emoji: '🪔', name: 'Diwali', telugu: 'దీపావళి', date: 'Nov 12' },\n";
    $jsContent .= "  { cat: 'festivals', color: '#ff5500', emoji: '🐘', name: 'Ganesh Chaturthi', telugu: 'వినాయక చవితి', date: 'Sep 18' },\n";
    $jsContent .= "  { cat: 'festivals', color: '#00aa55', emoji: '🥭', name: 'Ugadi', telugu: 'ఉగాది', date: 'Mar 22' }\n";
    $jsContent .= "];\n\n";
    
    // Auth Check
    $jsContent .= "if (typeof module !== 'undefined' && module.exports) {\n";
    $jsContent .= "  module.exports = { PRODUCTS, CATEGORIES, FESTIVALS };\n";
    $jsContent .= "}\n";

    // 4. Save to files (both in workspace and laragon if it exists)
    $workspacePath = 'C:/Users/Laggoni chethan sai/trail web/js/products.js';
    if (file_exists(dirname($workspacePath))) {
        file_put_contents($workspacePath, $jsContent);
    }
    
    $laragonPath = 'C:/laragon/www/smps/js/products.js';
    if (file_exists(dirname($laragonPath))) {
        file_put_contents($laragonPath, $jsContent);
    }
}
